### ISSUE TITLE
Chrome Issue

### ISSUE THREAD

**Issue by swagkarna** [luck20yan/StealingPy#1]
It does not decrypt chrome passwords. It shows no chrome installed but i have chrome v 80

**Comment by luck20yan** [comment]
Thank you, I will try to understand the problem and figure it out

**Comment by swagkarna** [comment]
Actually chrome is not loated in user/appdata/roaming folder
its located in user/appdata/local folder
edit this in your script

**Comment by luck20yan** [comment]
Thanks
